### ISSUE TITLE
Issues with built REST URLs

### ISSUE THREAD

**Issue by cyplas** [ufal/pyclarindspace#7]
In trying this out for clarin.si, I'm having issues with run_examples.sh. My .env REPO_URL is https://www.clarin.si/repository, which results in a login attempt at https://www.clarin.si/rest/login instead of https://www.clarin.si/repository/rest/login. If I get rid of the use of urljoin in __init__ and also in api_post (see diff below), run_examples.sh logs in successfully but crashes soon after (apparently on the login page again):

```
 Traceback (most recent call last):
  File "example1.py", line 40, in <module>
    community = repository.find_or_create_community('test community')
  File "/home/cyp/pyclarindspace/clarindspace/_repository.py", line 116, in find_or_create_community
    return com if com is not None else self.create_community(name)
  File "/home/cyp/pyclarindspace/clarindspace/_repository.py", line 107, in create_community
    js = self.api_post('/communities', {'name': name})
  File "/home/cyp/pyclarindspace/clarindspace/_repository.py", line 50, in api_post
    r.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.clarin.si/repository/rest/login

```

Of course I haven't yet tried to systematically adjust urlparse.urljoin.

```
diff --git a/clarindspace/_repository.py b/clarindspace/_repository.py
index 65e3b06..5188643 100644
--- a/clarindspace/_repository.py
+++ b/clarindspace/_repository.py
@@ -20,7 +20,7 @@ class repository(object):
                 base_url (str): The repository url up to /rest or /xmlui
         """
         self._base_url = base_url
-        self._api_url = urljoin(base_url, 'rest/')
+        self._api_url = base_url + '/rest'
         self._token = None
         self._request_headers = None

@@ -43,7 +43,7 @@ class repository(object):
             args["headers"] = h

         args.update(kwargs)
-        api_url = urljoin(self._api_url, url.lstrip("/"))
+        api_url = self._api_url + '/login'
         r = requests.post(api_url, **args)
         _logger.debug(pformat(r))
         try:

```

**Comment by vidiecan** [comment]
have you tried using
 https://www.clarin.si/repository/
(mind the last slash)

**Comment by cyplas** [comment]
Yes, I have. This does work better than https://www.clarin.si/repository with the master version, but similar to my hacked version: it logs in successfully but then crashes soon afterwards (this time presumably due to //):

```
2017-10-04 17:19:28,683 Set log level to [10]
2017-10-04 17:19:28,683 Using [https://www.clarin.si/repository/] as repository url and [repo-admin@clarin.si] user
2017-10-04 17:19:28,685 Starting new HTTPS connection (1): www.clarin.si
2017-10-04 17:19:28,928 https://www.clarin.si:443 "POST /repository/rest/login HTTP/1.1" 200 56
2017-10-04 17:19:28,930 <Response [200]>
2017-10-04 17:19:28,930 User [repo-admin@clarin.si] successfully logged in
2017-10-04 17:19:28,931 Starting new HTTPS connection (1): www.clarin.si
2017-10-04 17:19:29,115 https://www.clarin.si:443 "GET /repository/rest//status HTTP/1.1" 404 985
2017-10-04 17:19:29,117 <Response [404]>
Traceback (most recent call last):
  File "example1.py", line 37, in <module>
    _logger.info(pformat(repository.login_status()))
  File "/home/cyp/work/langtech/clarin/lindat/rest-api/pyclarindspace/clarindspace/_repository.py", line 87, in login_status
    js = self.api_get('/status')
  File "/home/cyp/work/langtech/clarin/lindat/rest-api/pyclarindspace/clarindspace/_repository.py", line 31, in api_get
    r.raise_for_status()
  File "/home/cyp/.pyenv/versions/2.7.13/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.clarin.si/repository/rest//status
```

**Comment by vidiecan** [comment]
those two `//` are not an issue  (unless you have something special in your web server conf) but I fixed it anyway

**Comment by vidiecan** [comment]
@cyplas seems you have something special in your web server conf; anyway, try now please and close if it works

**Comment by cyplas** [comment]
Hmm, I'm glad I don't have to dig into our server configs, as it works now, thank you!
